### ISSUE TITLE
SMC Draft Rollout Plan for State Officers

### ISSUE THREAD

**Issue by LizLeBreton** [CMSgov/CMCS-DSG-DSS-Oversight#101]

**Comment by LizLeBreton** [comment]
**Brief description of the task** 

We need a draft SMC Rollout Plan that leverages the channels and process from our Governance Plan. The SMC rollout plan needs to be tailored to States as the audience and provide them with enough information to understand SMC and the process associated with it (including the documents needed for certification, and all the required elements). 

**What steps are needed to make it a reality?**
- [x] Share the link to the current versions of the [Streamlined Modular Certification materials](https://partners.mitre.org/sites/AMITExternal/MITRE%2018F%20and%20MPR%20Collab/Forms/AllItems.aspx?RootFolder=%2Fsites%2FAMITExternal%2FMITRE%2018F%20and%20MPR%20Collab%2FStreamlined%20Modular%20Certification%20Package%20Materials&FolderCTID=0x012000CF61D7475E25F046B2ACE76397B4D5D1&View=%7B59517B94%2D94DC%2D49ED%2DBF75%2D84D45601521B%7D) 
- [ ] Johanna and others to coordinate and begin drafting the SMC Rollout Plan for State Officers
- [ ] SMC Wiki shared with State Officers
- [ ] High level SMC overview PowerPoint shared with State Officers
- [ ] Liz and Sam to review and approve SMC Rollout Plan

**Comment by awodarekoreilly** [comment]
@LizLeBreton i'm thinking the description should reference SOs as the audience instead of states. i'll create a new issue for the state-focused version.

**Comment by LizLeBreton** [comment]
@awodarekoreilly fixed!
