### ISSUE TITLE
Finalize & share Zenhub/Github "rules of the road" 

### ISSUE THREAD

**Issue by artfulaction** [CMSgov/CMCS-DSG-DSS-Oversight#141]
Post Zenhub governance information to CMS Github, where it can be accessed and used.

[Who is the user or audience?] CMS + Contractors

**What steps are needed to make it a reality?**
- [x] 18F Test plan with Liz and Sam
- [x] Liz + Sam send line edits and roles and responsibilities
- [x] 18F Incorporate their feedback and make adjustments to plan
- [x] @artfulaction Make any needed edits to How to Use this Github page
- [x] @LizLeBreton Present plan in cross-team meeting
- [x] @artfulaction publish plan on Github wiki
- [x] @LizLeBreton make any final tweaks in Github, if needed
- [x] @LizLeBreton share link to Github page in Teams (& maybe plan to walk through it in more detail in next cross-team mtng?)

**Please tag with the following labels (if relevant)**

- Assignee
- Contractor lead
- Epic (if applicable)

**Comment by amyashida** [comment]
@LizLeBreton and @sjschaffzin40 we're blocked here waiting on you

**Comment by alexpandel** [comment]
hey y'all, I tried to update the scope of this issue to reflect some of the decisions made this week... so I think @artfulaction you have the next step, and once you're done with that, you can re-assign this to @LizLeBreton and she can take it over the finish line (and either of you should feel free to adjust if I misinterpreted any next steps)!

**Comment by alexpandel** [comment]
ok, this is [up on Github here](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/Zenhub-Wiki-rules-of-the-road) 🎉 passing this off to you @LizLeBreton to see if there are any edits/next steps needed here, otherwise, feel free to close this issue when you feel good about it!

**Comment by nickm0511** [comment]
Thanks for the presentation on this yesterday @LizLeBreton. Just wanted to let you know we created a Certification Workstream page yesterday. It can be found [here](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/Certification-Workstream).
