### ISSUE TITLE
Create roll out plan for Health Rubric

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#145]
**Brief description of the task** 

We are getting ready to introduce the concept of the Rubric to SOs. This plan will help the Health Rubric team + Comms team align on: 
- Strategy
- Support materials
- Timing 
- Measuring success

**What steps are needed to make it a reality?**
- [x] 18F + CMS Decide on formats + workflows 
- [x] 18F + CMS Decide on success metrics 
- [x] 18F Draft roll out plan
- [x] 18F + CMS Discuss + finalize [roll out plan 🔒](https://docs.google.com/document/d/1Hzn0Gj0pJhOUoXJbbgFADrOeqEbDJ-LWEEhioUmHh94/edit#)
- [x] 18F update roll-out plan based on [decisions made 9/17 🔒](https://docs.google.com/document/d/1j5PGJ5USc7PcZFVQz0HcmMLHFcFNFNFzZ0VgpZOZqWw/edit#bookmark=id.aq8vnnj2o6hh)

**Comment by amyashida** [comment]
Drafting the roll out plan [here](https://docs.google.com/document/d/1Hzn0Gj0pJhOUoXJbbgFADrOeqEbDJ-LWEEhioUmHh94/edit)

**Comment by amyashida** [comment]
18F sent roll out plan to CMS with specific questions called out on 9/9

**Comment by amyashida** [comment]
We discussed the plan and are moving forward with drafting content waiting for feedback on timeline and roll out details

**Comment by alexpandel** [comment]
Alright, decisions from our meeting this week are now reflected in [the roll out plan here 🔒](https://docs.google.com/document/d/1Hzn0Gj0pJhOUoXJbbgFADrOeqEbDJ-LWEEhioUmHh94/edit#heading=h.9fbi74rd9v2w). 2 questions:

1. should we get the roll-out plan our of Gdocs and onto the Github wiki (or Zenhub calendar)? 
2. Any other next steps here before we close this card, @amyashida?

**Comment by alexpandel** [comment]
ok, added the release plan to the wiki [here](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/Health-Tracker-release-timeline); closing this issue now!
