### ISSUE TITLE
Write Health Tracker one-pager for SO wiki

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#147]
**Brief description of the task** 

The wiki will provide SOs with background on the tool, an overview of how to use it, and suggestions for using the Tracker with their states. The goal is to provide SOs with the resources needed to feel confident using the Tracker. 

18F will draft the pages and then collect feedback and input from pilot SOs as well as the CMS workstream leads. 

**What steps are needed to make it a reality?**
- [x] Draft 1 page intro for wiki (with links to more info)
- [x] share 1-pager w/ Nick & Liz (& SO pilot partners?) for feedback by COB ET Mon 9/21

Must include: 
- Where to go for support

**Comment by amyashida** [comment]
There are some great talking points from one of our pilot SOs in [these notes](https://www.youtube.com/watch?v=NMIMB0sXF-I)

**Comment by artfulaction** [comment]
@amyashida I think that's the wrong link? It goes to a video on Zenhub.

**Comment by alexpandel** [comment]
FYI, I'm gonna ditch "Draft talking points for State Officers to use with states" from the checklist in favor of #95, since I think that's not needed for the _initial_ introduction on 9/29

**Comment by alexpandel** [comment]
heads up @amyashida, I took a second pass through [the indicators page draft 🔒](https://docs.google.com/document/d/1fZxhh0gO9s3JlRIzCOUgwPxNZxsda6B-nMiji-3MGzg/edit#heading=h.71f0oern6fy) for the wiki. Assigning to you for a review, and if these edits look good to you, feel free to resolve them and then we can share with N&L (/, C&D?) for feedback!
