### ISSUE TITLE
Prep for SO skill building 

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#148]
**Brief description of the task** 

We know many of the concepts in the health rurbic are new for SOs. In order to enable SOs to confidently use the rubric  we will focus on building skills/knowledge in those areas.

**What steps are needed to make it a reality?**
- [x] 18F to draft learning cohort outline
- [x] 18F to draft syllabus outline
- [x] 18F to share draft for feedback
- [x] Meet with L+N to review and incorporate feedback
- [x] Meet with L+N to align on cohort SO expectations

**Comment by amyashida** [comment]
Matt is taking lead on this

**Comment by jadudm** [comment]
Testing.

**Comment by alexpandel** [comment]
@jadudm @amyashida are y'all still using this issue to track work? is this one up to date?

**Comment by NAretakis** [comment]
Pretty sure this is done. Closing now but y'all can reopen if it ain't.
