### ISSUE TITLE
Prep MVP Airtable views for release

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#150]
**Brief description of the task** 

Explore options for displaying health data for SOs once an SO has entered data via the Airtable form. 

End user: SOs

**What steps are needed to make it a reality?**
- [x] 18F share options with Nick & Liz Tues 9/22 for feedback
- [x] create gallery view for each state/territory
- [x] @artfulaction explore options in Airtable for the kind of filtering Nick suggested

**Comment by alexpandel** [comment]
FYI @artfulaction, creating this task to reflect your work on this! feel free to update to be more accurate (I just took a stab)

**Comment by amyashida** [comment]
@NAretakis each state has a gallery view now - closing this out
