### ISSUE TITLE
Measure baseline SO confidence in primary indicators

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#151]
**Brief description of the task** 

Identify which core indicators SOs feel most/least confident about so we can prioritize upskilling efforts

Gather info from SOs, 18F/Ops team use data 

**What steps are needed to make it a reality?**
- [ ] create plan for measurement (by 10/6)
- [ ] share plan with N&L for feedback (on 10/6) 
- [ ] get feedback from CMS (during 10/8 sync)
- [ ] adjust plan based on feedback 
- [ ] do the measuring!

**Comment by alexpandel** [comment]
Matt Jadud and I will pair on this one!

**Comment by amyashida** [comment]
we are doing this embedded in the SO MD kickoff
