### ISSUE TITLE
Write SO wiki page about primary health indicators

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#154]
**Brief description of the task** 

This wiki page will provide SOs with additional info about the primary indicators. The goal is to provide SOs with the resources needed to feel confident using the Tracker. 

**What steps are needed to make it a reality?**
- [x] @alexpandel Draft overview of/background on indicators for wiki
- [x] @amyashida resolve edits 
- [x] share w/ CMS for feedback
- [x] CMS publish on wiki (and link out from Health Tracker one-pager)
- [x] CMS link this page to the one-pager on the wiki (#153)

**Comment by alexpandel** [comment]
heads up @amyashida, I took a second pass through [the indicators page draft 🔒](https://docs.google.com/document/d/1fZxhh0gO9s3JlRIzCOUgwPxNZxsda6B-nMiji-3MGzg/edit#heading=h.71f0oern6fy) for the wiki. Assigning to you for a review, and if these edits look good to you, feel free to resolve them and then we can share with N&L (/, C&D?) for feedback!

**Comment by alexpandel** [comment]
now that this one is already published on the CMS Sharepoint wiki, I'm reassigning this issue to @NAretakis and @LizLeBreton to make sure the main wiki one pager gets posted as well (#153), and that this indicators page gets linked out from there!

**Comment by NAretakis** [comment]
Page drafted and posted.
