### ISSUE TITLE
Identify Examples and Lessons Learned from SMC/States to Highlight for State Officers

### ISSUE THREAD

**Issue by LizLeBreton** [CMSgov/CMCS-DSG-DSS-Oversight#157]
- [x] MITRE to develop a synopsis of certification states and lessons-learned that can be shared with State Officers on 11/10 MES All Teams Call. MITRE will send materials to CMS for review by 11/2.
- [ ] CMS to review and share with State Officers via a Wiki entry, presentation, or other venues (TBD)

**Comment by jbcannon313** [comment]
We will add @Millerkp Kyle Miller for these lessons learned, also I'm not sure we are using the term hybrid anymore

**Comment by nickm0511** [comment]
MITRE will attend color team calls next week to follow-up on the All Teams Call discussion that occurred today.

**Comment by nickarrow** [comment]
Cleaning up board, closing issue.
