### ISSUE TITLE
Get new 18F team member access to shared spaces

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#158]
18F is onboarding a new team member and he will need access to Teams, Zenhub, and potentially the sharepoint wiki 

**What steps are needed to make it a reality?**
- [x] CMS to add Matt to Github repo
- [x] CMS to add Matt to Teams
- [ ] CMS to add Matt to sharepoint access group

**Comment by nickm0511** [comment]
@amyashida, happy to help get him on the Partner site - what is his email address?

**Comment by NAretakis** [comment]
Final step is getting Matt access to sharepoint.

**Comment by NAretakis** [comment]
@jadudm should have an invite link now (via email), and that should get you into SharePoint.
