### ISSUE TITLE
Give feedback on streamlining modular certification "punch list" 

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#160]
**Who is the user?** 

_end user_ is states & SOs (by way of CMS & MITRE)

**What is the benefit to them?**
 
this should help CMS plan what additional materials will need to be developed/provided to states & SOs to support them in streamlining Modular Certification

From @nickm0511: "goal of the doc is to highlight where on the streamlining modular certification journey map [Mural](https://app.mural.co/t/advmedit1916/m/advmedit1916/1595596093748/3cb0abf06efd602d63a3a7ca702ce47051b8cf52) there appear to be areas where we need more process definition (and tools), either to help SOs, help states, or just to simply help better define how a certain mechanism within the process should work. The idea is that we could then take this punch list to discuss where there are opportunities to collaborate across ONETEAMDSG to better define all of the details."

**What steps are needed to make it a reality?**

- [x] 18F review [the document 🔒](https://partners.mitre.org/sites/AMITExternal/_layouts/15/WopiFrame.aspx?sourcedoc=%7B9EA15B49-E31D-4140-AC1E-5D2429ED07DF%7D&file=Streamlining%20modular%20certification%20Mural%20punch%20list_10.8.2020.docx&action=default&CT=1602177585196&OR=DocLibClassicUI), the version entitled "10.8.2020," with a focus on: are there other places in the Mural that look like we need to do something or not? And where can we be vague or not?
- [x] 18F decide whether feedback can be shared via doc comments, or whether a discussion would be more effective
- [x] 18F share the feedback (ideally by EOD Fri 10/9)
- [x] MPR review " "

**Comment by amyashida** [comment]
18F has added our feedback as comments/additions to the doc!

**Comment by awodarekoreilly** [comment]
I’ve added comments to the doc from both Ben and myself. We also have a few higher-level comments on the process, which are at the bottom of the document for further consideration. @nickm0511 @moelrich @nickm0511
