### ISSUE TITLE
Develop Learning cohort Blurb/Pitch for Team Leads

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#161]
SOs and Team Leads need a brief description of the Health Tracker Learning Cohort so they can recruit SOs to be a part of it and SOs can know what they are volunteering for.

Per conversation. Either a paragraph, or perhaps a really short video?

- [x] 18F to draft content and share with CMS
- [x] CMS to share with Team Leads / SOs

**Comment by amyashida** [comment]
Matt and I sent the blurb over to CMS on 10/9!

**Comment by NAretakis** [comment]
Shared with Team Leads!
