### ISSUE TITLE
Develop initial lessons for SO, M.D, Learning cohort

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#162]
SOs need training and support to build confidence using the Health Tracker with their states. 

18F is developing training materials for the first cohort. 

**What steps are needed to make it a reality?**
- [x] Agree on the cohort model/expectations
- [ ] 18F draft initial lessons 
- [ ] CMS provide feedback on initial lessons
- [ ] 18F + CMS decide where materials will live

**Comment by jadudm** [comment]
This was too broad. Created separate tickets.
