### ISSUE TITLE
MITRE & DSG to attend color team meetings for conversation/FAQ on certification

### ISSUE THREAD

**Issue by jbcannon313** [CMSgov/CMCS-DSG-DSS-Oversight#172]
To help level set with the SOs (the audience) on the certification transition and streamlining cert process, MITRE/DSG will: meet with the color teams to go over the wikis and go over Qs and As. 

- [ ] SOs will be asked to review the wikis prior to the discussion (include link in appt)
- [ ] MITRE will pull out talking points for the discussion @jbcannon313 
- [ ] MITRE will consolidate Qs and As to place on the wiki @jbcannon313 /Sandy
- [ ] DSG will set up color team meetings, dates/calendar appointments, copy MITRE @LizLeBreton

**Comment by NAretakis** [comment]
@LizLeBreton to revise this issue with some specifics.

**Comment by nickm0511** [comment]
Liz mentioned this would likely happen in 2 or 3 weeks from now.
