### ISSUE TITLE
Add link to SO MD site to Github wiki 

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#174]
**Brief description of the task** 

Add link to live and editing site so N+L can have an easy editing process

live: http://go.usa.gov/xGhKc
editing: https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/site/jadudm/cms-htmd/admin/#/

**Comment by artfulaction** [comment]
Added to the wiki: https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/Health-Tracker-course

Also listed on the main Health Tracker page under deliverables: https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/MES-Health-Tracker
