### ISSUE TITLE
Get local version running on @artfulaction's machine

### ISSUE THREAD

**Issue by artfulaction** [CMSgov/CMCS-DSG-DSS-Oversight#177]
**Brief description of the task** 

Go through site content and structure 

**What steps are needed to make it a reality?**
- [x] Princess review site, note changes
- [x] Matt and Princess collaborate to go through and make changes
- [ ] Get local version running on Princess' machine to make future changes

**Comment by jadudm** [comment]
I'm exploring some setup questions with colleagues in Solutions. The last element of this ticket is still underway. 

The solution might be "Matt and Princess spend more time screen sharing the terminal."

**Comment by jadudm** [comment]
Closing this ticket. Will handle as part of writing of care and feeding document, which will require testing.
