### ISSUE TITLE
Document Review Workflow for N+L

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#180]
Lets write up a page where we describe the workflow, and share that with them.

It could even be part of the site. 

Or, it could be a README-type document.

Either way, something that spells out the new, improved, simplified process. Perhaps with links to the staging/live sites.

**Comment by jadudm** [comment]
Drafted, tossed out to the group.

> Suggested (simplified) workflow:
> 
> 1. We will will work on a "staging" site. 
> 2. When we post new lessons, we'll create a Zenhub ticket and ping you in Teams.
> 3. You give a look, and send us comments and feedback anyway you feel comfortable. Email, Teams, carrier pigeon...
> 4. We iterate. 
> 5. When it's good, we close the ticket.
> 
> This involves no new tools or technology on your part, and keeps it simple.
> 
> We will merge things from the staging site into the live site as we go, so that pieces are revealed one step at a time. Those merges will only happen after signoff.
> 
> Links for these things are in the Github wiki:
> 
> FIXME
> 
> For reference, the staging site:
> 
> http://go.usa.gov/x7CUB
> 
> The live site:
> 
> http://go.usa.gov/xGhKc

**Comment by amyashida** [comment]
this looks good to me! what do we need to close this? do we want feedback from @NAretakis and @LizLeBreton ?

**Comment by amyashida** [comment]
Anything we need to do to close this?
