### ISSUE TITLE
Track resource usage throughout courses

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#188]
Currently, all resources are in the YAML datafile.

We should add a "dimension" or "row" key to each resource. This can then reference the rubric elements. For example:

```
        - title: So You Want to Be A Product Manager
          uid: sywtbapm
          url: https://beingfa.com/2017/10/31/so-you-want-to-be-a-product-manager/
          author: Julia Austin
          note: "There are core competencies that every PM must have – many of which can start in the classroom – but most are developed with experience and good role models/mentoring..."
```

should become

```
        - title: So You Want to Be A Product Manager
          uid: sywtbapm
          url: https://beingfa.com/2017/10/31/so-you-want-to-be-a-product-manager/
          author: Julia Austin
          note: "There are core competencies that every PM must have – many of which can start in the classroom – but most are developed with experience and good role models/mentoring..."
          dimensions:
             - oo1.1
             - pf2.2
```

The result would be that we can track where resources are used, and then render the resources list on a lesson-by-lesson basis. We could also have a "Resources referenced in this lesson" linkset at the bottom of each lesson.

- [ ] Add dimensions to existing resources list (_data/resources.yaml)
- [ ] Reorganize resources page under 4 primary indicator headings
- [ ] Add description of resources page to the top blurb
- [ ] Explore the "resources referenced" section at the bottom of each lesson

**Comment by artfulaction** [comment]
I'm thining once this structure is set up I'll add the page description to the top of Resources.

**Comment by jadudm** [comment]
We think the following:

1. This was a nice idea at the time.
2. No one seems to be using the Resources list based on interactions. (That's not hardcore UX work, BTW.)
3. It isn't structured well for use.
4. It might as well go away.

We're going to unlink it. However, the DB of resources is *still necessary*, because pages look up links in it.
