### ISSUE TITLE
Style list/guide for streamlining mod cert CIB, CIB guidance, wikis, training

### ISSUE THREAD

**Issue by jbcannon313** [CMSgov/CMCS-DSG-DSS-Oversight#191]
To have consistency across documents we need to have a style list/guide that we can maintain and update, acronym list. This will benefit state officers, states, and one team DSG

- MITRE will start a style guide @jbcannon313 /Sandy  
- MITRE and DSG will review first draft @LizLeBreton @sjschaffzin40 
- DSG will circulate style guide to other partners for reviews and additions @LizLeBreton 
- MITRE will play revised style guide on wiki and monitor for additions/changes @jbcannon313 /Sandy

**Comment by LizLeBreton** [comment]
@jbcannon313 - please pause on this. We already have 18F and the Content Support Center (DSG contract) working on this.

**Comment by jbcannon313** [comment]
@LizLeBreton sorry I was unclear. We have a style guide that we have been using for the CIB, CIB guidance document and training decks. This task is just to share what we have so other contractor has. Thanks

**Comment by NAretakis** [comment]
Thank you for raising this, Nick & Eugene & Liz convened and we are going to close this task as we have other issues to cover style principles and guide work. At this time we do not need additional resources working on this task.
