### ISSUE TITLE
Synthesize 18F feedback

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#2]
**Who is the user?** 
18F team, SOs

**What will this help them do?**
Ensure the [feedback we gathered from 18F](https://github.com/18F/cms-oversight/issues/20) is meaningfully incorporated into our work moving forward

**When is it needed?**
~ async synthesis by 6/12; next steps w/ Nick & Liz by 6/16?

**What steps are needed to make it a reality?**
- [x] @amyashida pull her highlights from the [notes](https://docs.google.com/document/d/1RYKv-6FOO-fkU-jnTx57ImMcOERuAVn1fbh7pbyVwmo/edit) into [Mural](https://app.mural.co/t/gsa6/m/gsa6/1591629385814/fc09a89bafd7558f034071fbe5dc03bb6e0d70d8) 
- [x] @alexpandel pull her highlights from the [notes](https://docs.google.com/document/d/1RYKv-6FOO-fkU-jnTx57ImMcOERuAVn1fbh7pbyVwmo/edit) into [Mural](https://app.mural.co/t/gsa6/m/gsa6/1591629385814/fc09a89bafd7558f034071fbe5dc03bb6e0d70d8) 
- [x] group & label key insights & prep for discussion w/ Nick & Liz
- [x] discuss & decide on next steps w/ Nick & Liz
- [x] turn next steps into Github issues
- [x] @amyashida take a pass through [the draft summary](https://docs.google.com/document/d/1YUE1OaqSzpoaKm8AFKwDRHc7Kl-wUitR310MaH0FpRU/edit) 
- [x] @alexpandel publish summary in Github wiki

**Comment by amyashida** [comment]
Turned next steps into [#53 ], [#54 ],[#51], [#9]

**Comment by alexpandel** [comment]
alright @amyashida, took a first pass at this [in here](https://docs.google.com/document/d/1YUE1OaqSzpoaKm8AFKwDRHc7Kl-wUitR310MaH0FpRU/edit); reassigning this to you to take a pass through in the morning and make sure you feel 👍 about it, and then feel free to reassign back to me and I can get it into the wiki!

**Comment by alexpandel** [comment]
Thank you for the suggestions this afternoon @amyashida! I went ahead and threw the latest draft [onto the wiki here](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/MES-Health-Rubric-research-findings-(Jun-'20)), but feel free to keep iterating if you think it needs further edits!

**Comment by alexpandel** [comment]
closing this for now, but @amyashida feel free to keep tweaking the summary as you see fit!
