### ISSUE TITLE
Thumbs Up / Thumbs Down on Course 1, Lesson 2

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#201]
The lesson is available on the preview (staging) site:

[https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/course/one/capacity/](https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/course/one/capacity/
)

A message in the Teams channel for 18F + y'all is a good place for conversation. Or, if it is more natural/easier, add comments/feedback to the ticket here.

Close the ticket with a comment saying "Looks Good!" or similar if it looks ready to go.

**Comment by NAretakis** [comment]
Good to go. I'll be curious to see how the conversations go because there are so many projects. But picking 1 or 2 and talking it through with folks seems like a great way to get at it.
