### ISSUE TITLE
Plan vendor meeting on testing

### ISSUE THREAD

**Issue by awodarekoreilly** [CMSgov/CMCS-DSG-DSS-Oversight#206]
- [x] Talk to PSTG 
- [ ] Ed to talk to PSTG Exec Board
- [ ] Pick meeting date in January (postponed from December)
- [ ] Send meeting announcement to Ed
- [ ] Approve meeting announcement and send

**Comment by nickarrow** [comment]
Cleaning up board, closing issue.
