### ISSUE TITLE
Conduct meeting inventory + needed meetings across workstreams

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#210]
**Brief description of the task** 

Make sure we are collaborating at the right level on the right things with the right people

**What steps are needed to make it a reality?**
- [x] 18F to make list of current + proposed meetings
- [x] Discuss with CMS
- [x] Rearrange calendar invites

**Comment by amyashida** [comment]
You can access via [google docs](https://docs.google.com/document/d/1mzmw5U5wxcQJGrTvq_lzOSIEJ7WezYCg4F2i3TkvmLY/edit#heading=h.xab5mye7i76b) or attached here.[https://app.zenhub.com/files/269427572/3492dfc9-6b6c-418d-94af-1544494faa48/download](https://app.zenhub.com/files/269427572/3492dfc9-6b6c-418d-94af-1544494faa48/download)

**Comment by amyashida** [comment]
We can discuss tomorrow during our call if we need to adjust anything - next steps are speaking with CMS!

**Comment by alexpandel** [comment]
@NAretakis I'm doing some board cleanup, and just noticed this card has been hanging out in this column for _months_ — how are we feeling about our meeting cadence? Anything we want to change? Maybe we can capture some proposed changes [in the doc](https://docs.google.com/document/d/1mzmw5U5wxcQJGrTvq_lzOSIEJ7WezYCg4F2i3TkvmLY/edit) and discuss at our next meeting? cc @amyashida
