### ISSUE TITLE
Lesson 3 from Course 1: Thumbs Up? Comments? Etc.

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#211]
Lesson 3 in staging: [https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/course/one/procurement/](https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/course/one/procurement/)

Comments on this thread, or just close it out. I'll see if I can track it/get a notification from Zenhub. :)

**Comment by NAretakis** [comment]
Course looks really good. With only a suggestion to the section below. I feel like most of our experiences are shruggies and not anger. Any particular reason for that particular language choice?

"...it just kind of left you 🤷‍♂️ "

![Screen Shot 2020-11-03 at 12.36.49 PM.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/1fde7eca-82b3-4579-acac-7a655270cef7)

**Comment by jadudm** [comment]
Good question. When writing, especially in contexts like this, I tend to imagine that I'm saying it... but, the emphasis in spoken word can be very different than writing.

I'll tweak that.

**Comment by jadudm** [comment]
Revised to:

"and therefore, you were just kind of like... <b>shrug</b>?"

**Comment by NAretakis** [comment]
Thank you. Good to go. @jadudm
