### ISSUE TITLE
Update Design Principles based on feedback

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#218]
**Brief description of the task** 

Take the output of the Design Principles workshop and distill into principles and applications that can be shared/posted somewhere. 

**What steps are needed to make it a reality?**
- [x] Transfer output into a doc
- [x] Iterate on themes - turning into principles
- [x] Workshop principles with core group
- [x] seek feedback from wider 18F team
- [ ] incorporate feedback from 18F team (11/25 coworking meeting)
- [x] Share revised principles with feedback group and collect feedback
- [ ] incorporate feedback from feedback group
- [ ] Post principles somewhere they can be referenced

**Comment by amyashida** [comment]
Output of the workshop has been transferred to [this doc ](https://docs.google.com/document/d/1HhFPS2jbf8-yjxoimnywD5wyDwIPzSo3sMS21vjFiQs/edit#)for further iteration

**Comment by amyashida** [comment]
Next steps in prep for Monday w/ core team: 

1. Potential additional principles for consideration that didn't make as we moved through the workshop
2. Minimal wordsmithing just on the design principles themselves. Potentially short descriptive text for folks to respond to. 
3. Examples of unintended consequences

**Comment by alexpandel** [comment]
made a call for feedback & possible unintended consequences from broader 18F team; will plan to incorporate their feedback on Friday in time to bring revised principles back to the core team on Monday!

**Comment by amyashida** [comment]
@NAretakis shared with a broader CMS group on 11/24

**Comment by amyashida** [comment]
Prep for 11/25: 

- Update principles mural to reflect current principles
- Drop 18F feedback into mural 

11/25 w/. John and Nick: 
- synthesize feedback into themes
- apply themes to principles

**Comment by alexpandel** [comment]
oh whoops, missed this card when I made #235 🤦‍♀️  Since #235 is now more up to date than this one, I'm gonna close this one in favor of #235!
