### ISSUE TITLE
Conduct research for 2nd Service Design Workshop

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#219]
**Brief description of the task** 

The goal of our second workshop is to create a future state map of MES oversight. In order to do this successfully as a group there is a lot of research and prep that needs to happen. 

The overall research plan can be viewed[ here](https://docs.google.com/document/d/1zzyFLMYnfFTropdP5UMMtULp3kOCKMcOTHFkLvJ8nuc/edit). 

We can mine existing efforts and research to: 
- Utilize existing maps and research to identify pain points and understand emotions
- Identify current touch points and channels
- Pull core principles, hypothesis, value propositions, and desired emotional states

**What steps are needed to make it a reality?**
- [x] Create and agree on research plan
- [ ] Schedule interviews
- [x] Review existing artifacts (to be tracked in separate issues)
- [ ] Conduct interviews

**Comment by alexpandel** [comment]
the scope of this changed a little along the way ([current research plan is here](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/MES-Oversight-Service-Design#timeline)); calling this done for now!
