### ISSUE TITLE
Draft and send homework for 12/9 workshop

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#221]
**Brief description of the task** 

In order to have the most valuable workshop we will need participants to do some prep work

**What steps are needed to make it a reality?**
- [x] Draft homework
- [x] Get feedback from core team
- [x] Send homework

**Comment by alexpandel** [comment]
FYI, working on fleshing this out [in here 🔒](https://docs.google.com/document/d/1zT9x70L8mTYF_nb_vON8mfIvLIaqyid_Z0JEGs5HJak/edit#bookmark=id.ehslg1b7ix5h)
