### ISSUE TITLE
Gather and link or send existing artifacts for Service Design research

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#223]
**Brief description of the task** 

We want to make sure that future state proposals are informed by current/past efforts and hypothesis. In order to do this we need to gather existing artifacts and talk to folks about them!  

We will use the [MES Service Design Research Mural](https://app.mural.co/t/gsa6/m/gsa6/1604938922214/fc403913fc5bb6c04350501bca97737ab0c4fa76) to track identified efforts/artifacts that we should learn more about. 

**What steps are needed to make it a reality?**
- [ ] Each of them needs a link to the artifact (share in Teams and we will upload them to the shared drive) and a point of contact. 
- [ ] If the point of contact is not on the team, we will also need an intro email so we can schedule an interview. 

**Artifacts/efforts we need links or contacts for**
- [ ] MITRE state feedback
- [ ] SMC pilot findings (is this the same thing as above?)
- [ ] NPRM subreg guidance list
- [ ] Florida surveys
- [ ] SO surveys + retro boards
- [ ] CMS/A1M state research from 2019

**Comment by amyashida** [comment]
@NAretakis I would tag John and Paul here but I don't see them in github?

**Comment by alexpandel** [comment]
calling this "done enough!"
