### ISSUE TITLE
Facilitator's Guide

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#232]
A guide for 18Fers (or someone else) for how to guide/lead discussions w/ the SOs.

**Comment by jadudm** [comment]
This is partially authored in the "principles" document.

It should be moved into the site (the principles matter), and then a facilitator's guide page should be provided as well. 

These can all fall under "Resources." There's no reason for this content to be separate from the site.

**Comment by jadudm** [comment]
See also #194

**Comment by artfulaction** [comment]
Can add:

- Here's how often we meet, the schedule, etc
- Here's how we recap the sessions and incorporate feedback.
- Assume this will change over time and incorporate flexibility into the guidelines
