### ISSUE TITLE
Review of Lesson 4

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#236]
Yep. We didn't have a lesson four review ticket. 

https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/rubric/id-high-1/

It's a short lesson. We'll use it as a way to have the cohort do some synthesis across all that they've discussed so far.

**Comment by NAretakis** [comment]
Reviewed, this is good to go. @jadudm 

I'll also probably share the video around other places too.
