### ISSUE TITLE
Revise/finalize FOSS lesson.

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#250]
What it says. It is done, but it needs one more set of eyes.

**Comment by jadudm** [comment]
https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/preview/jadudm/cms-htmd/staging/courses/six/overview/

**Comment by artfulaction** [comment]
Looks good! Closing this.
