### ISSUE TITLE
Course 2, Lesson 1 Feedback/Checkoff

### ISSUE THREAD

**Issue by jadudm** [CMSgov/CMCS-DSG-DSS-Oversight#260]
If it's good to go, close the ticket. Leave comments and leave it open if there's things to say/note/change.

https://federalist-eb7b399c-56d9-4c6b-b524-27e0627cdd86.app.cloud.gov/site/jadudm/cms-htmd/rubric/oo-high-2/

**Comment by NAretakis** [comment]
Catching up. Good to go.
