### ISSUE TITLE
Document possibilities for using Airtable for prioritized HT features

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#270]
**Brief description of the task** 

Based off of user feedback we prioritized new/updated features on the [HT roadmap.](https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1596569564270/d3c81a141ea72d7b6c2db90da408f1b68d3c6ea0). Many of these features require some decisions on how we'd like to use Airtable moving forward. 18F will document these decision points so the HT team can choose the best way to move forward. 

**What steps are needed to make it a reality?**
- [x] Outline decision points
- [x] Discuss w/ Nick, Liz, Sam
- [ ] Decide + break out implementation tasks

**Comment by alexpandel** [comment]
@amyashida should we throw this one back into the 30 day backlog while we figure out HT/dashboard next steps in light of the SD workshop?
