### ISSUE TITLE
look through other supplemental material for CIB to ensure everything aligns with health work

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#56]
[docs here](https://partners.mitre.org/sites/AMITExternal/MITRE%2018F%20and%20MPR%20Collab/Forms/AllItems.aspx?RootFolder=%2Fsites%2FAMITExternal%2FMITRE%2018F%20and%20MPR%20Collab%2FStreamlined%20Modular%20Certification%20Materials&View=%7B59517B94%2D94DC%2D49ED%2DBF75%2D84D45601521B%7D)

**Comment by NAretakis** [comment]
This tabled while the SMC content is being drafted.

**Comment by nickarrow** [comment]
Cleaning up board, closing issue.
