### ISSUE TITLE
Kick off oversight content governance process development

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#57]
**Who is the user?**
content consumers (State Officers & states) & content creators (CMS, MITRE, Mathematica & 18F)

**What will this help them do?**
- helps CMS ensure that any content and resources designed for states & State Officers are clear, consistent, and reinforcing (vs confusing or conflicting)
- helps teams who are creating content for states & State Officers understand the expectations and approval process for that content

**What steps are needed to make it a reality?**
- [x] @LizLeBreton check on when Sam is going to be back & tell @amyashida & @alexpandel 
- [x] schedule 90-min(?) kickoff session (week of 7/20?)
- [x] @alexpandel & @amyashida pull in 18F content strategist & get them up to speed (#60) 
- [x] @alexpandel & @amyashida & Princess to prep content for kickoff
- [x] have kickoff!
- [x] capture next steps in repo!

**Comment by LizLeBreton** [comment]
I'm here - @alexpandel and @amyashida are you able to find me now?

**Comment by alexpandel** [comment]
iiinteresting, it looks like I can tag you in a comment @LizLeBreton, and can assign you to a task, but I can't tag you in the _body_ of the issue? WEIRD!! @NAretakis any idea what might be going on here?

**Comment by alexpandel** [comment]
update — looks like I _can_ tag you in the issue body, it just doesn't autosuggest you, I have to type your name out completely... probably just a glitch, I bet it will resolve itself moving forward. glad to have you in here, @LizLeBreton! 🎉

**Comment by alexpandel** [comment]
#68 is the next step here!
