### ISSUE TITLE
map out overall strategy for communicating process changes to SOs & states

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#58]
**Who is the user?**
SOs & states (by way of DSG leadership)

**What will this help them do?**
- DSG leadership will have a shared understanding of who needs to hear what and when so they can develop the content needed at the right time.

**What steps are needed to make it a reality?**
- [x] iterate on [existing Mural](https://app.mural.co/t/gsa6/m/gsa6/1593055020698/cc48bb9dda84c36e1eca768242bc520217815f64)
- [x] share with Nick & Liz for feedback in 6/25 sync & decide on next steps
- [x] add next steps to Github

**Comment by alexpandel** [comment]
heads up @amyashida, I moved the comms strategy content into [this Mural](https://app.mural.co/t/gsa6/m/gsa6/1593055020698/cc48bb9dda84c36e1eca768242bc520217815f64) and tried reorganizing it a little.

I didn't get the chance to actually go through it all though (was more focused on setting up scaffolding) — **would really appreciate your 👀 & 🧠 on it in the morning if you have time. Particular areas that could use extra attention:**
 - I added a row for "channel/venue" to make space to specify where those particular actions/comms would happen (e.g., in a team-wide meeting; a 1:1 meeting; in a document via the wiki; via email; etc etc), and one for "key messages" to make space for capturing any top-level instincts about the most important message to support each action/quell each concern; let me know if those actually make sense to you, or if they feel out of place.
- I tried to rearrange things to make it clearer that we really think we shouldn't be trying to roll out process changes at scale (i.e., via CIBs or other guidance) _before_ we've even finished piloting them, but I can't tell if where I landed makes that clear enough at first glance — genius ideas for visual ways to underline that point even more are v much welcome!

**Comment by amyashida** [comment]
I really like these changes and additions! Made a few minor tweaks. My only thought here is that I don't want to communicate that we feel confident about what is in the grey box. We've done it once now but now we know that we can do it better with their help.

**Comment by alexpandel** [comment]
YES, greeeeat point. I almost wanted to have separate "do it once", "do it 5-10 times", and "fully scale it" sections, since I agree that just these two pilots is NOT enough to be ready to scale it to everyone... let's discuss with them!
