### ISSUE TITLE
Add content about how to use the repo/wiki

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#66]
**Who is the user?**
DSG Oversight teams

**What will this help them do?**
Make sure everyone is on the same page about how to get started using Github

**When is it needed?**
Goal for 7/16

**What steps are needed to make it a reality?**
- [x] draft content
- [x] review content with Nick
- [] Nick made edits and share

**Comment by NAretakis** [comment]
Done!
