### ISSUE TITLE
Capture current content/training process

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#67]
**Who is the user?**
18F, Opps team, Orange Workstream

**What will this help them do?**
Documenting the current process will help us understand what we can build on in the future

**What steps are needed to make it a reality?** 

- [x] Meet with Nick + Sam to get a tour of current state
- [x] Map out model of existing process
- [x] discuss and edit model with Opps team

**Comment by NAretakis** [comment]
Looks great.

**Comment by alexpandel** [comment]
we've done enough work on this for now; will likely circle back to mapping out the new process in more detail in the near future, but we'll create a new ticket for that when it comes back up!
