### ISSUE TITLE
Start mapping interim content/training governance process

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#68]
**Who is the user?**
Opps team, all MES Oversight teams

**What will this help them do?**
Work effectively within a content governance process to make sure content is tested with end users and end users have what they need to be successful.

**What steps are needed to make it a reality?**
- [x] Build off model of current process for interim process
- [x] Share/collect feedback with Liz + Sam
- [x] Liz + Sam share with MES Oversight teams
- [x] Clean up MVP doc

**Comment by amyashida** [comment]
18F: 
- Add column to table in doc and send back

Need CMS input on: 
- Should narrative info live on github?
- Adding what stage things are in to the "what's in flight" table 

For discussion on Thursday 8/6:
- What format should "in flight" table  live in - spreadsheet?

**Comment by alexpandel** [comment]
@artfulaction this particular ticket is done now, yeah? and next steps are #92, #93 & #94, is that right?

**Comment by artfulaction** [comment]
Yes, those are the next steps! I think this ticket will be done after we meet Thursday afternoon, then its work will move on mostly to #94
