### ISSUE TITLE
Identify ways to link/incorporate testing materials within active development guide

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#70]
**Who is the user?**
States + SOs

**What will this help them do?**
- Implement new testing guidance
- Evaluate how well their state is implementing the guidance 
- Evaluate the health of their state's testing practices

**What steps are needed to make it a reality?**

- [x] 18F to review testing guidance
- [ ] Clarify timelines for testing guidance [#80]( https://app.zenhub.com/workspaces/cmcs-dsg-dss-oversight-5f1915977f0e450022da42dc/issues/cmsgov/cmcs-dsg-dss-oversight/83)
- [x] Identify places to link directly vs develop training for guidance

**Comment by amyashida** [comment]
This has evolved into [#83 ]( https://app.zenhub.com/workspaces/cmcs-dsg-dss-oversight-5f1915977f0e450022da42dc/issues/cmsgov/cmcs-dsg-dss-oversight/83).

**Comment by alexpandel** [comment]
closing since this is now duplicative with #83
