### ISSUE TITLE
Create a Map of State of All Active State Pilots

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#75]
We want to create a wiki entry that shows a map of all the active state pilots that our oversight work is engaged in. 

**What steps are needed to make it a reality?**
- Get list of pilots from Green
- Get list of pilots from Blue
- Get list of pilots from Orange
- Put them all together on a wiki entry

**Comment by nickarrow** [comment]
Cleaning up board, closing issue. This is now mapped in our active projects list.
