### ISSUE TITLE
Figure out a shared central storage location

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#79]
**Brief description of the task** 
We need a place to centrally store all of the related documents for our work. It needs to be accessible to everyone, but also secure since there are works-in-progress.

**What steps are needed to make it a reality?**
- [x] Fill out this checklist @NAretakis 
- [x] Research options for file storage
- [x] Pick one
- [x] Roll it out to the Oversight Team

**Comment by nickm0511** [comment]
On the MITRE side we have our Partner SharePoint site we have been using with CMS to store our in-progress SMC materials. That site requires users to request access to view/edit the documentation. Just throwing that out as an option.

**Comment by NAretakis** [comment]
@nickm0511 I think that is actually the most viable option if it will allow MPR and 18F folks in as well. Could we setup a "Shared Documents" type structure for the oversight work that can have subfolders for organization?

**Comment by nickm0511** [comment]
@NAretakis, yes, we have had some folks from MPR use our external Partner site in the past (and Eugene and I believe Ed have been using it as well). If that is the direction we want to head I can edit the site to accommodate folders for each organization.

**Comment by NAretakis** [comment]
@nickm0511  - let's do it. Get the larger oversight team access to it, and folders for organization. That would be a great win and much needed. Can you pull the tigger on making this happen?

**Comment by NAretakis** [comment]
@nickm0511 - let me know when this is ready for prime time, and we can roll it out to the larger MES team.

**Comment by NAretakis** [comment]
Yay! We have a thing! Thanks Nick M!

**Comment by nickm0511** [comment]
Np!
