### ISSUE TITLE
Iterate on DDI rubric in prep for pilot

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#8]
**Who is the user?** 
18F team, SOs 

**What will this help them do?** 
Ensure we're ready to start piloting

**When is it needed?** 
By 7/2 meeting with Nick & Liz

**What steps are needed to make it a reality?** 
- [x] finish adding "why it matters" to [each key signal](https://app.mural.co/t/gsa6/m/gsa6/1593627219860/24d48fac2cd81e50723ca27920677c4b6bf94ba2)
- [x] ensure all our [core health indicators](https://docs.google.com/document/d/1W0luHCE69XQwfuuIA4dueLBwZOkMP28LA4VxmvZ0vgM/edit) are represented
- [x] draft research questions/prompts for inquiry about the rubric
- [x] get initial feedback from Nick & Liz (in 7/2 meeting)

**Comment by alexpandel** [comment]
alright @amyashida, I took another pass through, but it currently still feels _really_ messy. Like, 100% will confuse SOs massively in its current state, and I'm not even sure how to coherently talk about the state it's in with N&L tomorrow. Hoping you might have some epiphanies in the morning; here are my breadcrumbs:

What I did:
- Tried to reorganize everything around the core health indicators
- Pulled out anything that didn't feel like a top priority or felt more appropriate for a different stage in the lifecycle ("discards" are to the right of the main board)
- Looked back at our [initial rubric scratchpad](https://app.mural.co/t/gsa6/m/gsa6/1589296239298/cfea49ef3e77d42e824966bb7b91322a52356736) to make sure we weren't missing any major sub-points

What still needs work: 
- the "how to find out" section is a mess; it's currently a mix of notes-to-self about what signal we're actually talking about, plus actual ways to suss that info out, and the significance of horizontal and vertical stacking is not consistent throughout the doc. if I had more time I would have tried to clean this up; apologies for the mess.
- I re-used some of the red/yellow/green stickies from the original Rosetta Stone in places where they _sorta_ fit, but many of them don't feel like a perfect fit right now. Ideally we would go through the whole thing again, and get it to a place where we feel really confident that 1) we're calling out the right signals; 2) we're giving clear direction on where to look to assess each signal; and 3) we feel solid about the red/yellow/green examples for each signal. Right now my confidence level in each individual sticky is all over the place; for now, the stickies that are italicized are ones where I'm trying to say "this one is basically a placeholder and needs to change", and the non-italicized ones mean "I feel relatively good about this one" 🤷‍♀️

Sorry to leave you with a big hairball, this is a LOT to try to make sense of in 24 hours! 😅
