### ISSUE TITLE
Split out the Testing Guidance Framework into 1) SMC Testing Content and 2) A Separate CIB on Concepts like Agile, CI/CD, DevOps, etc. 

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#80]
**Brief description of the task** 

Split out the Testing Guidance Framework into 1) SMC Testing Content and 2) A Separate CIB on Concepts like Agile, CI/CD, DevOps, etc.

**What steps are needed to make it a reality?**

- [x] Update this issue/checklist to reflect who is doing the various parts of this work (MPR, 18F, MITRE, CMS)

- [x] @egabriyel, @moelrich, @nickm0511, and Hatem met on 8/7 to discuss plan

- [x] Split out the Testing Guidance Framework into 1) SMC Testing Content and 2) A Separate CIB on Concepts like Agile, CI/CD, DevOps, etc.

- [x] MITRE to draft a revised version of the 1) SMC Testing Content and incorporate content into drafting 2) A Separate CIB on Concepts like Agile, CI/CD, DevOps, etc.

- [x] MITRE to send both 1 and 2 to @egabriyel to review

- [x] @egabriyel to review 

- [x] CMS meeting with Kaitlin and Vidit on 8/25 on Modern Trends in Software Development document

- [x] Kaitlin and Vidit on 8/25 to provide feedback on the Modern Trends in Software Development document

- [x] Refine content

- [x] With @egabriyel and Ed to review

Then do #90

**Comment by hghafir** [comment]
Making progress on the new content. For now, I am putting the new content in the existing Testing Guidance document. The idea is seeing all the content together in the same place may give us a better idea about how to split it. One thing of notice is that the new content is not necessarily about "testing" but about modern development approaches to increase quality. I am writing about Agile methodology, Design Thinking, DevOps, CI/CD, and Automation. So, calling it SMC-CIB and Testing-CIB is not indicative, and we will need to come up with a better name once we decide on the content split.

I plan to distribute a first draft for an initial look later in the week,

**Comment by nickm0511** [comment]
@hghafir sent to @egabriyel to review on 8/5.
