### ISSUE TITLE
Choosing States for OBP Pilots

### ISSUE THREAD

**Issue by medicaidsarah** [CMSgov/CMCS-DSG-DSS-Oversight#81]
**Brief description of the task** 

States need to be selected for 2 OBP pilots and pitches made to seek their commitment to participate.

**Who is the user or audience?**

DSG Leadership Team
State Officers for Chosen States
OBP Pilot Team (TBD members)

**What steps are needed to make it a reality?**

- [x] Framework for criteria to evaluate candidate states proposed by @medicaidsarah
- [x] Framework populated with candidate states by DSG
- [x] Swap out Louisiana as no longer viable option @medicaidsarah 
- [x] Develop pitch for each candidate state by end of week of 8/17 @medicaidsarah
- [x] DSG chooses two states to pitch to, and state officers set up meetings (new issues opened at that point to track progress separately)

**Comment by medicaidsarah** [comment]
@egabriyel and @NAretakis - now that I have been schooled in the ownership of issues and how to alert team members to take the next step... <drum roll please> - Team DSG is up next on advancing this work.  Can you provide an ETA for when the framework will be completed with candidate states to consider?

Thanks!

cc:  FYI @moelrich and @nickm0511

**Comment by nickm0511** [comment]
https://app.zenhub.com/files/282989047/b203d141-a309-4d3e-96bd-a6627f82ae35/download

**Comment by ChrisLPeterson** [comment]
Two states chosen -- Idaho and Virginia -- and pitches made:
~9/20/20 to Idaho
10/14/20 to Virginia

I'll open 2 new issues to track progress separately
