### ISSUE TITLE
Refine Health Rubric to Incorporate Testing Guidance

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#83]
**Brief description of the task** 

Coordinate efforts between the Health Rubric and the Testing Guidance so that these two things are synchronized. 

**What steps are needed to make it a reality?**
- [x] Meet with Testing Guidance team
- [x] Review Hatem's doc
- [x] Draft one or two high level questions for the rubric
- [x] Share with Testing Guidance team

**Comment by amyashida** [comment]
Incorporated here: https://app.mural.co/t/gsa6/m/gsa6/1593627219860

collecting some feedback from 18F folks

**Comment by alexpandel** [comment]
@NAretakis, what should be our next step here? is this done?

**Comment by NAretakis** [comment]
Done! However, the roadmap stuff and refinements are our next steps (which are already issues in GH).
