### ISSUE TITLE
Conduct retro of health pilots so far and align on plan for next steps

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#86]
**Brief description of the task** 

18F has been running pilots with VT + NY's SOs for the last few months. We want to stop and reflect on how they are going, if there are changes we should make moving forward, and align on new opportunities that have been presented. 

The end users of this are the Health Team

**What steps are needed to make it a reality?**
- [ ] Conduct retro with SOs, Liz + Nick
- [ ] Identify any changes that need to be made
- [ ] Document changes in issues or in the wiki

**Comment by alexpandel** [comment]
@amyashida should we close this one, since we've already iterated on the mode of engagement here?
