### ISSUE TITLE
SharePoint Wiki Update Entry for Certification Talking Points

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#89]
**Brief description of the task** 

Need to create a wiki entry on the MES Wiki for SOs. The purpose is for SOs to have the talking points for states who are asking how they should get their system certified, how they should engage with us since MECT/MEET is being retired, and what the clear next steps are for the state and State Officer to certify systems in the interim. 

**What steps are needed to make it a reality?**
- [x] Talking points and content are created
- [x] Talking points and content is provided for @egabriyel to review
- [ ] Talking points are posted on the SharePoint wiki page

**Comment by NAretakis** [comment]
@moelrich - just checking on how this one is progressing. Are there any blockers?

**Comment by nickm0511** [comment]
@NAretakis, @moelrich and @nickm0511 are meeting with @egabriyel today to review the draft we sent over.
