### ISSUE TITLE
Identify supporting materials that may be needed for in-flight rubric

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#9]
**Who is the user?** 
- SOs

**What will this help them do?** 
Build skills needed to assess in-flight projects

**When is it needed?** 
Aim to have first pass done 7/3

**What steps are needed to make it a reality?** 
- [x] 18F Review Rosetta Stone and identify material 
- [x] Review Rosetta Stone w/ Nick and Liz and identify material
- [x] Review Rosetta Stone w/ SOs and identify material

**Comment by NAretakis** [comment]
Is this done? If not, what is this? @alexpandel

**Comment by alexpandel** [comment]
yeah, let's call this done for now, I think the "why this matters" links cover this for now!
