### ISSUE TITLE
Create first draft of style guide

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#92]
**Brief description of the task** 

Audience: Sam + Liz, MES Oversight contractors, internal SMEs 

Draft a style guide to set guidelines for consistent voice/tone across messaging + content release. 

**What steps are needed to make it a reality?**
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nickarrow** [comment]
Cleaning up board, we have a style guide for oversight work!
