### ISSUE TITLE
Add questions to the SMC Journey Map

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#97]
**Brief description of the task** 

Audience: questions are for MITRE's considerations
Description: add comments/questions to the journey map 

**What steps are needed to make it a reality?**
- [x] 18F to review journey map and add comments/questions
- [x] Mathematica to review journey map and add comments/questions

**Comment by NAretakis** [comment]
I've added all my comments into the SMC journey map... not 18F... but just letting folks know my comments are in there. @medicaidsarah

**Comment by MathBenFisch** [comment]
Mathematica review done.

**Comment by alexpandel** [comment]
@amyashida's done hers and I'm doing a second pass now, will comment when done!

**Comment by alexpandel** [comment]
alright @medicaidsarah, 18F team had added some comments & Qs. thanks again for sharing!!
