### ISSUE TITLE
Synthesize & summarize DDI rubric feedback

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#98]
**Who is the user?** 
State Officers (via the MES health team)

**What will this help them do?**
Ensure the feedback we gathered from our SO pilot partners about the DDI rubric (#54) is meaningfully incorporated into the next iteration 

**What steps are needed to make it a reality?**
- [x] @alexpandel pull in insights from [this deck 🔒](https://docs.google.com/presentation/d/1YPFXoycuERq9vaVrrc9EeJgCe2FirVQsTxCJ36-29eQ/edit) and from last few weeks of interviews into [this Mural 🔒](https://app.mural.co/t/gsa6/m/gsa6/1597345429363/2f0646646b9a895974aba04380e43aa0669cdeac) 
- [x] @alexpandel share progress w/ Amy & Princess 
- [x] pull in stickies from this week's interviews into the Mural (the ones _without_ ✔️s in [this doc 🔒](https://docs.google.com/document/d/11oFZexfFM6UQDK1_wJxuMksLnl_2koe802ImcXiP2ow/edit#))
- [x] @amyashida & @artfulaction do some async processing (before 8/26)
- [x] (someone — Alex?) take first, async stab at drafting agenda for 8/27 CMS mtng (incorporate next steps from @amyashida's questions doc)
- [x] 18F team meet to review where we landed with synthesis and confirm agenda for CMS mtng (on 8/26)
- [x] meet w/ Nick & Liz to discuss & decide on next steps (on 8/27)
- [x] draft up a research summary a la [this last one](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/MES-Health-Rubric-research-findings-(Jun-'20))
- [x] turn next steps into Github issues

**Comment by amyashida** [comment]
Research summary posted here: https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/MES-Health-Rubric-research-findings-(Aug-'20)
