### ISSUE TITLE
Draft SMC Rollout Plan for States

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#99]
**Brief description of the task** 

We need a draft SMC Rollout Plan that leverages the channels and process from our Governance Plan. The SMC rollout plan needs to be tailored to States as the audience and provide them with enough information to understand SMC and the process associated with it (including the documents needed for certification, and all the required elements). 

**What steps are needed to make it a reality?**
- [x] Share the link to the current versions of the [Streamlined Modular Certification materials](https://partners.mitre.org/sites/AMITExternal/MITRE%2018F%20and%20MPR%20Collab/Forms/AllItems.aspx?RootFolder=%2Fsites%2FAMITExternal%2FMITRE%2018F%20and%20MPR%20Collab%2FStreamlined%20Modular%20Certification%20Package%20Materials&FolderCTID=0x012000CF61D7475E25F046B2ACE76397B4D5D1&View=%7B59517B94%2D94DC%2D49ED%2DBF75%2D84D45601521B%7D) 
- [x] Johanna, Ben, Amy, and others to coordinate and begin drafting the SMC Rollout Plan for States
- [x] Kyle to send pilot PPT to team
- [x] Amy/Ben assess materials and create draft for team review
- [x] Amy to schedule recurring meeting "SMC rollout: SOs and States"
- [x] Liz and Sam to review and approve SMC Rollout Plan

**Comment by MathBenFisch** [comment]
Added my name as the Mathematica point person.

**Comment by awodarekoreilly** [comment]
Completed on 9/11
